language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
  - '5'
  - '4'
before_script:
  - npm install -g bower polymer-cli
  - bower install
  - sudo apt-get install oracle-java8-set-default
script:
  - xvfb-run polymer test
